### ISSUE TITLE
Change Column Headings from Letters to Numbers #Hacktoberfest

### ISSUE THREAD

**Issue by MarkAnthonyNgo** [MarkAnthonyNgo/Sudoku#3]
Easy task.
All you have to do is change the column headings from letters to numbers in the Sudoku.c file.
Happy coding!
#Hacktoberfest

**Comment by JamesMCo** [comment]
I'll take this one on! Do you want the headings to run from 0 to 8, or 1 to 9? Or maybe something else entirely :-P

**Comment by 0raghvendrrao** [comment]
I would feel happy to fox it.

**Comment by MarkAnthonyNgo** [comment]
Issue has been resolved!
